#pragma once
#include <stdio.h>
#include <stdlib.h>
#define DIRECTINPUT_VERSION 0x0800
#include <dinput.h>

#if DIRECTINPUT_VERSION == 0x0700
typedef HRESULT(WINAPI* LPFNDIRECTINPUTCREATE)(HINSTANCE, DWORD, LPVOID*, LPUNKNOWN);

EXTERN_C LPFNDIRECTINPUTCREATE lpDICreate;
EXTERN_C HRESULT DirectInputCreateImpl(HINSTANCE hinst, DWORD dwVersion, LPVOID* ppDI, LPUNKNOWN punkOuter);
#elif DIRECTINPUT_VERSION == 0x0800
typedef HRESULT(WINAPI* LPFNDIRECTINPUTCREATE)(HINSTANCE, DWORD, REFIID, LPVOID*, LPUNKNOWN);

EXTERN_C LPFNDIRECTINPUTCREATE lpDICreate;
EXTERN_C HRESULT DirectInputCreateImpl(HINSTANCE hinst, DWORD dwVersion, REFIID riidltf, LPVOID* ppvOut, LPUNKNOWN punkOuter);
#endif